export const posts = [
  {
    slug: 'software-that-endures',
    title: 'Software That Endures: Writing Systems for the Next Decade',
    excerpt: 'Most codebases die within three years. The ones that survive share a handful of quiet disciplines — none of which are glamorous, all of which are learnable.',
    category: 'Technology',
    author: 'Elena Moreau',
    date: 'March 12, 2026',
    readTime: '8 min read',
    cover: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=2000&q=80',
    featured: true,
    content: [
      { type: 'p', text: 'We are often asked what separates a codebase that will still be running a decade from now from one that will be rewritten within three years. The honest answer is: very little that is exciting.' },
      { type: 'h2', text: 'The Discipline of Boring Choices' },
      { type: 'p', text: 'Longevity in software comes from a series of unremarkable decisions: choosing a mainstream database over a novel one, writing tests before they are required, documenting intent rather than implementation. Each decision, taken in isolation, feels small. Aggregated over years, they are the difference between a system that is cherished and one that is endured.' },
      { type: 'quote', text: 'The code you will regret is rarely the code you found hard to write. It is the code you found easy.' },
      { type: 'h2', text: 'Three Principles We Hold To' },
      { type: 'p', text: 'Across every engagement, we return to the same three principles. They are not original. They are, however, applied inconsistently — and the cost of that inconsistency is measured in quarters, not sprints.' },
      { type: 'ul', items: [
        'Optimize for the reader, not the writer. Code is read an order of magnitude more often than it is written.',
        'Prefer explicit over clever. Cleverness ages poorly; clarity does not.',
        'Invest in boundaries. Strong module boundaries are what make rewrites possible without full replacements.',
      ]},
      { type: 'p', text: 'None of this will make for a memorable conference talk. It will, however, make for a codebase your successors will thank you for.' },
    ],
  },
  {
    slug: 'hospitality-as-design',
    title: 'Hospitality as Design: Rethinking the Guest Interface',
    excerpt: 'A hotel is, in the end, an interface between a human and a place. The best ones are designed with the same rigor as the best software.',
    category: 'Hospitality',
    author: 'Javier Ruiz',
    date: 'February 27, 2026',
    readTime: '6 min read',
    cover: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2000&q=80',
    content: [
      { type: 'p', text: 'Spend a week running a small hotel and a curious thing happens: you start to see every interaction as an interface. The check-in desk is a form. The room key is a handshake. The minibar is a menu in three dimensions.' },
      { type: 'h2', text: 'The Quiet Power of Defaults' },
      { type: 'p', text: 'In software design, we talk about defaults because most users never change them. In hospitality, the principle is identical: the vast majority of guests will experience exactly what you chose for them. The room temperature at arrival. The folding of the first towel. The font on the welcome card. None of these are small decisions.' },
      { type: 'quote', text: 'A great property is not the sum of its amenities. It is the sum of its defaults.' },
      { type: 'h2', text: 'What We Learned Operating' },
      { type: 'p', text: 'When ARK began operating properties, our early assumption was that the technology would be the differentiator. It is not. The technology matters, but it matters in exactly the way that good operating systems matter to the software running on them: invisibly, reliably, and only noticed when absent.' },
      { type: 'p', text: 'The differentiator, we came to understand, is judgment — applied thousands of times per day, by trained people, within a thoughtfully designed system.' },
    ],
  },
  {
    slug: 'the-quiet-portfolio',
    title: 'The Quiet Portfolio: Why We Take Fewer Engagements',
    excerpt: 'There is a particular kind of work that can only be done when the number of clients is small. This is a note about why we chose that constraint.',
    category: 'Practice',
    author: 'Sofia Clements',
    date: 'February 10, 2026',
    readTime: '5 min read',
    cover: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=2000&q=80',
    content: [
      { type: 'p', text: 'Early in our practice, we received more inbound inquiries than we could responsibly serve. The temptation was to scale. We chose instead to become harder to hire.' },
      { type: 'h2', text: 'Scarcity as a Feature' },
      { type: 'p', text: 'Taking fewer engagements is not a marketing posture. It is an operating constraint with consequences: we know every client by name; a partner is on every call; and the work we refuse to do is as carefully chosen as the work we accept.' },
      { type: 'quote', text: 'The best studios we admired were not the largest. They were the ones where you could still get the founder on the phone.' },
      { type: 'h2', text: 'The Trade-off' },
      { type: 'p', text: 'The trade-off is real. We turn down work that would be lucrative. We decline engagements we are capable of delivering. And we say no to relationships that would be flattering. But the alternative — becoming a machine that optimizes for utilization — would erase the thing we started ARK to protect.' },
    ],
  },
  {
    slug: 'capital-with-conscience',
    title: 'Capital With Conscience: Notes on Financial Craft',
    excerpt: 'Financial work is not morally neutral. The models we build, the advice we give, and the deals we enable all leave a mark. We take that seriously.',
    category: 'Finance',
    author: 'Marcus Aden',
    date: 'January 22, 2026',
    readTime: '7 min read',
    cover: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=2000&q=80',
    content: [
      { type: 'p', text: 'There is a myth, particularly in financial services, that numbers are objective. They are not. Every model is a series of choices about what to include, what to omit, and how to weight what remains. Those choices carry values.' },
      { type: 'h2', text: 'The Assumptions Page' },
      { type: 'p', text: 'We have a habit at ARK. Every financial model we deliver begins with a page titled, plainly, "Assumptions." Not buried in a footnote, not hidden behind a tab — the first page a reader sees. The discipline is simple: if we cannot defend an assumption in the open, we should not rely on it in the model.' },
      { type: 'quote', text: 'A model is a story told with numbers. Be honest about which story you are telling.' },
      { type: 'h2', text: 'What Conscience Looks Like in Practice' },
      { type: 'p', text: 'It looks like declining a mandate when the structure would be extractive. It looks like flagging risks to the buyer that the seller would rather we not. It looks like slower work, fewer deals, and a reputation that compounds quietly over years.' },
    ],
  },
  {
    slug: 'teaching-what-we-do',
    title: 'Teaching What We Do: The Case for Practitioner Education',
    excerpt: 'The best education we received never came from a classroom. It came from watching someone senior do the work, and being asked to try it ourselves.',
    category: 'Education',
    author: 'Ana Villar',
    date: 'January 05, 2026',
    readTime: '6 min read',
    cover: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=2000&q=80',
    content: [
      { type: 'p', text: 'When we began offering courses, we made a deliberate choice: every instructor would be a practicing operator, designer, or engineer at ARK. No career educators. No professional curriculum writers. The people teaching the work would be the people doing it.' },
      { type: 'h2', text: 'The Apprenticeship Model, Updated' },
      { type: 'p', text: 'What we are building is, at its core, an apprenticeship. Live work. Shared over the shoulder. Case studies that are still unfolding as we teach them. The cohorts are small because intimacy is the medium.' },
      { type: 'quote', text: 'You cannot learn craft from a recorded lecture. You can only learn it by watching craft being performed, and being asked to try it yourself.' },
      { type: 'h2', text: 'Who It Is For' },
      { type: 'p', text: 'Our programs are not for everyone. They are for people who already have a career, who are serious about their craft, and who are looking for the kind of mentorship that is difficult to find once one has outgrown an entry-level job. If that sounds like you, we would be pleased to have a conversation.' },
    ],
  },
  {
    slug: 'architecture-of-trust',
    title: 'The Architecture of Trust in a Multidisciplinary Firm',
    excerpt: 'Running a firm across software, real estate, and finance creates a particular challenge: how do you build trust across disciplines that do not share a language?',
    category: 'Practice',
    author: 'Elena Moreau',
    date: 'December 14, 2025',
    readTime: '9 min read',
    cover: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2000&q=80',
    content: [
      { type: 'p', text: 'There is a standard piece of advice given to professional service firms: specialize. Pick one thing. Go deep. It is good advice, and for most firms, it is the right advice. We chose not to take it.' },
      { type: 'h2', text: 'Why Breadth' },
      { type: 'p', text: 'Our clients are rarely single-discipline problems. A hotel opening is a real estate decision, a software decision, a finance decision, and a design decision — and the quality of the outcome depends on those decisions being made in conversation with one another. A single-discipline firm cannot hold that conversation. We can.' },
      { type: 'quote', text: 'The interesting problems live at the seams. Single-discipline firms do not work at the seams; they work around them.' },
      { type: 'h2', text: 'The Cost' },
      { type: 'p', text: 'Breadth is expensive. It requires hiring expensive people. It requires them to respect one another across disciplines they do not share. And it requires partners who can hold the whole thing in their head. We believe the cost is worth it. Our clients, so far, have agreed.' },
    ],
  },
];

export function getPost(slug) {
  return posts.find(p => p.slug === slug);
}
